fix minio ci

diff --git a/.github/actions/s3-setup/action.yml b/.github/actions/s3-setup/action.yml
--- a/.github/actions/s3-setup/action.yml
+++ b/.github/actions/s3-setup/action.yml
@@ -25,17 +25,26 @@ runs:
     - name: Start MinIO server
       run: |
         docker run -d \
-          --network=host \
+          -p 9000:9000 \
           --name minio \
           -e "MINIO_ROOT_USER=OjezEU7caGd8H9zSG4Ov" \
           -e "MINIO_ROOT_PASSWORD=9tWu8XB8Cemol44pVGd661ZkyAwJ1OPNd6BC0tmH" \
           quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1 \
-          server /data --console-address ":9001"
+          server /data
       shell: bash
 
     - name: Wait for service readiness
       run: |
-        until curl -s http://localhost:9000/minio/health/live; do sleep 5; done
+        timeout=60
+        interval=5
+        until curl -s http://localhost:9000/minio/health/ready; do
+          sleep $interval
+          timeout=$((timeout - interval))
+          if [ $timeout -le 0 ]; then
+            echo "MinIO failed to start in time"
+            exit 1
+          fi
+        done
       shell: bash
 
     - name: Configure MinIO client
